name: Affichage Push/Commit

on:
  push:
    branches:
      - "**"  # Toutes les branches

jobs:
  afficher_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Affichage du commit
        run: |
          echo " Nouveau push détecté !"
          echo " Auteur : ${{ github.actor }}"
          echo " Message du commit : ${{ github.event.head_commit.message }}"
          echo " Branche : ${{ github.ref }}"
