on:
  workflow_dispatch:  # Déclenchement manuel

jobs:
  travail_hybride:
    runs-on: ubuntu-latest
    steps:
      - name: Exécuter une commande dans la VM Ubuntu
        run: echo "Ceci s'exécute dans la VM Ubuntu"

      - name: Exécuter à l'intérieur d'un conteneur Alpine
        uses: docker://alpine:3.14  # L'image doit être accessible sans authentification
        with:
          entrypoint: /bin/sh
          args: |
            -c "echo 'Cette étape s'exécute dans un conteneur Alpine'"

      - name: Exécuter une autre commande dans la VM Ubuntu
        run: echo "Retour à la VM"
